import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'

const widget = readFileSync(new URL('../components/agent-chat-widget.tsx', import.meta.url), 'utf8')
const styles = readFileSync(new URL('../components/agent-chat-widget.module.css', import.meta.url), 'utf8')
const layout = readFileSync(new URL('../app/layout.tsx', import.meta.url), 'utf8')

test('business chat is available across every app page and separates asking, planning, and specialist work', () => {
  assert.match(layout, /<AgentChatWidget\s*\/>/)
  assert.match(widget, /chatRequest\(submittedMode, text, agentKey, context, history\)/)
  assert.match(widget, /businessAgentContext\(messages\.map/)
  assert.match(widget, /aria-label="Chat mode"/)
  assert.match(widget, />Ask<\/button>/)
  assert.match(widget, />Plan<\/button>/)
  assert.match(widget, />Work<\/button>/)
  assert.match(widget, /Choose business specialist/)
  assert.match(widget, /Auto-selected from your request/)
  assert.match(widget, /Auto select/)
  assert.match(widget, /BusinessAgentAnswer/)
  assert.match(widget, /proposal-only/)
  assert.match(widget, /Plan mode creates evaluated proposals for review/)
  assert.match(widget, /never approves or executes actions/)
  assert.match(widget, /Review \{proposed\.length\} saved/)
  assert.match(widget, /\/planning#console-token/)
})

test('Ask mode reads the whole app through /api/chat and links only to pages of the app', () => {
  const request = readFileSync(new URL('./chat-request.ts', import.meta.url), 'utf8')
  assert.match(request, /path: '\/api\/chat'/)
  assert.match(widget, /What I looked at/)
  assert.match(widget, /isLocalLink/)
  assert.match(widget, /href\.startsWith\('\/'\) && !href\.startsWith\('\/\/'\) && !href\.startsWith\('\/api\/'\)/)
  assert.match(widget, /never approves or changes anything/)
})

test('chat launcher and transcript have accessible, session-scoped controls', () => {
  assert.match(widget, /aria-haspopup="dialog"/)
  assert.match(widget, /aria-expanded=\{open\}/)
  assert.match(widget, /role="dialog" aria-modal=\{expanded \|\| undefined\} aria-labelledby="qs-chat-title"/)
  assert.match(widget, /aria-live="polite"/)
  assert.match(widget, /resolveConsoleAccess\(\)/)
  assert.doesNotMatch(widget, /localStorage|sessionStorage\.setItem/)
  assert.match(widget, /event\.key === 'Escape'/)
  assert.match(widget, /quicksilver:open-chat/)
  assert.match(widget, /aria-modal=\{expanded \|\| undefined\}/)
  assert.match(widget, /Expand chat to workspace/)
  assert.match(widget, /aria-label="Business workspaces"/)
  assert.match(widget, /\['\/','Overview','Company health and priorities'\]/)
  assert.match(styles, /\.panelExpanded/)
  assert.match(styles, /\.contextRail/)
  assert.match(styles, /@media \(max-width: 48rem\)\s*\{\s*\.launcher\s*\{\s*display:\s*none/s)
  assert.match(styles, /@media \(max-width: 38rem\)/)
  assert.match(styles, /@media \(max-width: 24rem\)/)
  assert.match(styles, /@media \(max-height: 32rem\)/)
  assert.match(styles, /env\(safe-area-inset-bottom\)/)
})
